### PR TITLE
feat: new language icons

### PR DESCRIPTION
**Pull request by jzempel**
- [ ] **BREAKING CHANGE?** 

## Description

Add:
* `12/language-fill`
* `12/language-stroke`
* `16/language-fill`
* `16/language-stroke`

## Checklist

* [x] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [x] :globe_with_meridians: SVG demo is up-to-date (`yarn start`)
* [x] :black_medium_small_square: Renders as expected in "dark" mode
* [x] :white_large_square: Renders as expected @ 2x scale

### CODE REVIEW

**Comment by jzempel** [comment]
Demo pre-published for review: https://garden.zendesk.com/svg-icons/

@CorbellaShelby the updated icons you sent me produced clean/quality SVGs.

**Comment by CorbellaShelby** [comment]
The fills look a bit odd. I'm going to redo the designs so they match the sets better

**Comment by jzempel** [comment]
@CorbellaShelby demo has your updated designs.

**Comment by jzempel** [comment]
@CorbellaShelby demo once again updated for review.

**Comment by CorbellaShelby** [comment]
I'm not seeing the fuzziness on 12px with my screen. All the assets are also sitting on full numbers on the grid + sizing. I've also spaced out the two horizontal lines.

**Comment by jzempel** [comment]
@allisonacs should these be named `globe`?

**Pull request merged**
