### PR TITLE
fix(sparkle icons): refine SVG paths

### PR DESCRIPTION
**Pull request by ze-flo**
## Description

- Updates SVG paths
- Optimize icons

## Detail

Screen Shot 2024-05-09 at 12 28 57 PM

## Checklist

* [ ] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [x] :globe_with_meridians: SVG demo is up-to-date (`npm start`)
* [x] :black_medium_small_square: Renders as expected in "dark" mode
* [x] :white_large_square: Renders as expected @ 2x scale

### CODE REVIEW

**Review by jzempel — APPROVED** [review]
...pending designer review

**Review by steue — CHANGES_REQUESTED** [review]
i know we’re on a tight timeline with this, but there some small adjustments for consistency with the rest of our icons. on the design side, we should fix:

1. the large sparkle in stroked versions. when adding icons to the library we aim to have the strokes within the pixel grid so they remain crisp in low resolution.

image

3. as much as possible, the stroked version should visually match the filled version.

image

ill reach out to Nathan as he isn't on github

**Comment by ze-flo** [comment]
@steue Icons have been polished and ready for your review. 🧼 ✨

**Review by steue — APPROVED** [review]
thanks all for the speedy work!!!

**Pull request merged**
