### PR TITLE
feat: add `circle-full`, `location`, `notes`, and `slight-smiley` icons

### PR DESCRIPTION
**Pull request by jzempel**
- [ ] **BREAKING CHANGE?** 

## Description

New icons include:

* `12-circle-full-stroke`
* `12-location-fill`
* `12-location-stroke`
* `12-notes-fill`
* `12-notes-stroke`
* `12-slight-smiley-fill`
* `12-slight-smiley-stroke`
* `16-circle-full-stroke`
* `16-location-fill`
* `16-location-stroke`
* `16-notes-fill`
* `16-notes-stroke`
* `16-slight-smiley-fill`
* `16-slight-smiley-stroke`

## Checklist

* [x] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [x] :globe_with_meridians: SVG demo is up-to-date (`yarn start`)
* [x] :black_medium_small_square: Renders as expected in "dark" mode
* [x] :white_large_square: Renders as expected @ 2x scale

### CODE REVIEW

**Comment by jzempel** [comment]
demo is pre-published for review: https://garden.zendesk.com/svg-icons/

**Comment by jzempel** [comment]
@allisonacs renamed per your request. I understand your `location` suggestion. But I can see this interfering with a future, literal `pin` object icon. 
download

**Comment by CorbellaShelby** [comment]
I agree with JZ. Pin is quite literal to the image is shows. Though, I do not have a secondary option to replace "location". Naming is hard...

**Comment by allisonacs** [comment]
Cool. Just wanted to make sure we were being purposeful :)

**Pull request merged**
