### PR TITLE
fix: clean up "sort" icons

### PR DESCRIPTION
**Pull request by jzempel**
- [ ] **BREAKING CHANGE?** 

## Description

* correct `12/sort-*.svg` widths
* right-size `16/sort-fill.svg`

## Checklist

* [x] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [x] :globe_with_meridians: SVG demo is up-to-date (`yarn start`)
* [x] :black_medium_small_square: Renders as expected in "dark" mode
* [x] :white_large_square: Renders as expected @ 2x scale

### CODE REVIEW

**Comment by jzempel** [comment]
The demo has been pre-published for review: https://garden.zendesk.com/svg-icons/

**Comment by CorbellaShelby** [comment]
Yea i'm getting that freaky icon too for some reason when I'm looking at:
https://garden.zendesk.com/svg-icons/16px/

**Comment by jzempel** [comment]
@allisonacs oops I published a screwed-up path. Sorry about that. It's corrected now.

**Comment by allisonacs** [comment]
😬 sorry for the delay

**Pull request merged**
