### PR TITLE
feat: new `cursor-arrow` and `megaphone` icons

### PR DESCRIPTION
**Pull request by jzempel**
- [ ] **BREAKING CHANGE?** 

## Description

Added:
* 12/cursor-arrow-fill.svg
* 12/cursor-arrow-stroke.svg
* 12/megapohone-fill.svg
* 12/megaphone-stroke.svg
* 16/cursor-arrow-fill.svg
* 16/cursor-arrow-stroke.svg
* 16/megapohone-fill.svg
* 16/megaphone-stroke.svg

## Details

Demo pre-published for review:
https://garden.zendesk.com/svg-icons/12px/
https://garden.zendesk.com/svg-icons/16px/

## Checklist

* [x] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [x] :globe_with_meridians: SVG demo is up-to-date (`yarn start`)
* [x] :black_medium_small_square: Renders as expected in "dark" mode
* [x] :white_large_square: Renders as expected @ 2x scale

### CODE REVIEW

**Comment by ginnywood** [comment]
Yes! It's only an issue on the 16px version, where the angle of the cursor “arrowhead” falls on a half pixel. I uploaded a new version with a different angle.

**Comment by jzempel** [comment]
ok @ginnywood @allisonacs – the icon has been updated and demo refreshed: https://garden.zendesk.com/svg-icons/16px/

**Comment by ginnywood** [comment]
Hooray, it looks much better! Thanks @jzempel. I just realized I forgot to update 16-cursor-fill to match the new angle—it's up now, could you update it as well? Sorry about that.

**Comment by jzempel** [comment]
@ginnywood ok, angle updated (demo, too) with the new fill icon.

**Comment by ginnywood** [comment]
🚀 thank you!

**Pull request merged**
